### ISSUE TITLE
Compiler breaks when rendering `[a][b]`, which is valid markdown

### ISSUE THREAD

**Issue by reyronald** [probablyup/markdown-to-jsx#226]
When trying to render the following valid markdown text the compiler fails unexpectedly.

```js
const React = require("react")
const { compiler } = require("markdown-to-jsx")

compiler("[one] [two]")
```

<details>
<summary>TypeError: Cannot read property 'target' of undefined</summary>

```
TypeError: Cannot read property 'target' of undefined
    at Object.e [as react] (https://6w4rkk8oxz.codesandbox.io/node_modules/markdown-to-jsx/dist/cjs.js:1:18047)
    at eval (https://6w4rkk8oxz.codesandbox.io/node_modules/markdown-to-jsx/dist/cjs.js:1:9670)
    at b (https://6w4rkk8oxz.codesandbox.io/node_modules/markdown-to-jsx/dist/cjs.js:1:8651)
    at b (https://6w4rkk8oxz.codesandbox.io/node_modules/markdown-to-jsx/dist/cjs.js:1:8560)
    at c (https://6w4rkk8oxz.codesandbox.io/node_modules/markdown-to-jsx/dist/cjs.js:1:10561)
    at compiler (https://6w4rkk8oxz.codesandbox.io/node_modules/markdown-to-jsx/dist/cjs.js:1:19495)
    at evaluate (https://6w4rkk8oxz.codesandbox.io/src/index.js:8:1)
    at pe (https://codesandbox.io/static/js/sandbox.62258a03.js:1:138332)
    at e.value (https://codesandbox.io/static/js/sandbox.62258a03.js:1:151187)
    at e.value (https://codesandbox.io/static/js/sandbox.62258a03.js:1:177403)
    at t (https://codesandbox.io/static/js/sandbox.62258a03.js:1:150975)
    at loadResources (https://6w4rkk8oxz.codesandbox.io/index.html:11:2)
    at evaluate (https://6w4rkk8oxz.codesandbox.io/index.html:17:3)
    at pe (https://codesandbox.io/static/js/sandbox.62258a03.js:1:138332)
    at e.value (https://codesandbox.io/static/js/sandbox.62258a03.js:1:151187)
    at e.value (https://codesandbox.io/static/js/sandbox.62258a03.js:1:177403)
    at e.value (https://codesandbox.io/static/js/sandbox.62258a03.js:1:177176)
    at https://codesandbox.io/static/js/sandbox.62258a03.js:1:99364
    at g (https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:207992)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:207780)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:208171)
    at u (https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:2891)
    at a (https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:2980)
```

</details>    
<br />

Here's a sandbox with the reproduction:

https://codesandbox.io/s/6w4rkk8oxz

**Comment by probablyup** [comment]
You aren’t providing a footnote. That’s footnote syntax.

**Comment by reyronald** [comment]
It may be, but I haven't seen any markdown engine blow up because of an incomplete syntax, and I don't think that's the expected behavior.

It should render gracefully to `[a][b]`, don't you think?

**Comment by probablyup** [comment]
This is out in 6.8.4 👍

**Comment by reyronald** [comment]
That's awesome @probablyup ! Thanks for your prompt response! 💪
