### ISSUE TITLE
Source first causes crash

### ISSUE THREAD

**Issue by vavra7** [probablyup/markdown-to-jsx#401]
When the very first thing I start to write in markdown is source then application crashes.

```
<Markdown>
   [1]: http://localhost:3000
</Markdown>
```
This results in:
```
Error: React.cloneElement(...): The argument must be a React element, but you passed null.
    at Object.cloneElement (webpack-internal:///../../node_modules/react/cjs/react.development.js:800:13)
    at Object.cloneElementWithValidation [as cloneElement] (webpack-internal:///../../node_modules/react/cjs/react.development.js:2274:33)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///../../node_modules/markdown-to-jsx/dist/index.module.js:7:14981)
    at processChild (webpack-internal:///../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (webpack-internal:///../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (webpack-internal:///../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (webpack-internal:///../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (webpack-internal:///../../node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at eval (webpack-internal:///./src/ServerApp.tsx:51:70)
    at Layer.handle [as handle_request] (/home/vavra/Projects/gemini/node_modules/express/lib/router/layer.js:95:5)
```

The issue occurs only when there is not yet any other markdown precedes the source.

markdown-to-jsx v7.1.3

**Comment by quantizor** [comment]
Should be fixed in v9
